/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    news: News;
    projects: Project;
    testimonials: Testimonial;
    promotions: Promotion;
    orders: Order;
    inquiries: Inquiry;
    'login-codes': LoginCode;
    contacts: Contact;
    expenses: Expense;
    quotes: Quote;
    jobs: Job;
    'outgoing-invoices': OutgoingInvoice;
    'inventory-items': InventoryItem;
    stocktakes: Stocktake;
    counters: Counter;
    'system-state': SystemState;
    'mail-log': MailLog;
    'push-subscriptions': PushSubscription;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'login-codes': LoginCodesSelect<false> | LoginCodesSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    expenses: ExpensesSelect<false> | ExpensesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'outgoing-invoices': OutgoingInvoicesSelect<false> | OutgoingInvoicesSelect<true>;
    'inventory-items': InventoryItemsSelect<false> | InventoryItemsSelect<true>;
    stocktakes: StocktakesSelect<false> | StocktakesSelect<true>;
    counters: CountersSelect<false> | CountersSelect<true>;
    'system-state': SystemStateSelect<false> | SystemStateSelect<true>;
    'mail-log': MailLogSelect<false> | MailLogSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'fr' | 'en') | ('de' | 'fr' | 'en')[];
  globals: {
    homepage: Homepage;
    about: About;
    'site-settings': SiteSetting;
    legal: Legal;
    integrations: Integration;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
  };
  locale: 'de' | 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Leer lassen = wird automatisch aus dem Titel erzeugt
   */
  slug?: string | null;
  category: number | Category;
  images: (number | Media)[];
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Preis in Euro, z.B. 1490.00. Bei Varianten gilt der Variantenpreis.
   */
  price?: number | null;
  /**
   * z.B. 150 für Speditionslieferung. Leer oder 0 = versandkostenfrei. Bei Abholung entfallen die Versandkosten automatisch.
   */
  shippingCost?: number | null;
  /**
   * z.B. Größen oder Ausführungen mit eigenem Preis
   */
  variants?:
    | {
        title: string;
        price: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Wählbare Farben (RAL o.ä.), ohne Aufpreis
   */
  colorOptions?:
    | {
        name: string;
        /**
         * z.B. #b32428 — für die Farbvorschau
         */
        hex?: string | null;
        id?: string | null;
      }[]
    | null;
  billOfMaterials?:
    | {
        item: number | InventoryItem;
        quantity: number;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  serviceProviders?:
    | {
        contact: number | Contact;
        /**
         * z.B. Verzinken, Pulverbeschichten, Lasern
         */
        service: string;
        cost?: number | null;
        /**
         * z.B. „10 Werktage" — geht in die zugesagte Lieferzeit ein.
         */
        leadTime?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * z.B. „3–4 Wochen". Jedes Stück wird einzeln gefertigt — leer lassen übernimmt den Standardwert aus den Website-Einstellungen.
   */
  productionTime?: string | null;
  /**
   * Steht fertig in der Werkstatt. Wird nach dem Verkauf automatisch auf „nicht verfügbar" gesetzt.
   */
  readyMade?: boolean | null;
  /**
   * Statt Warenkorb wird ein Anfrage-Button angezeigt
   */
  onRequestOnly?: boolean | null;
  available?: boolean | null;
  featured?: boolean | null;
  /**
   * Kleinere Zahl = weiter vorne in der Kategorie
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * z.B. "outdoor-moebel" — wird in der URL verwendet
   */
  slug: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Leer lassen für Hauptkategorien (erscheinen im Menü)
   */
  parent?: (number | null) | Category;
  /**
   * Kleinere Zahl = weiter vorne im Menü
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-items".
 */
export interface InventoryItem {
  id: number;
  name: string;
  type: 'material' | 'werkzeug' | 'maschine' | 'fertigware' | 'sonstiges';
  quantity: number;
  unit?: string | null;
  /**
   * Darunter erscheint der Posten in der Übersicht als knapp.
   */
  minQuantity?: number | null;
  /**
   * Einkaufspreis — Grundlage für die Bewertung zum Stichtag.
   */
  unitValue?: number | null;
  location?: string | null;
  /**
   * Bei Maschinen wichtig für die Abschreibung.
   */
  purchaseDate?: string | null;
  purchaseValue?: number | null;
  supplier?: (number | null) | Contact;
  /**
   * Nur bei fertigen Stücken, die im Shop stehen.
   */
  product?: (number | null) | Product;
  photo?: (number | null) | Media;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  name: string;
  role?: ('lieferant' | 'kunde' | 'dienstleister' | 'beides') | null;
  email?: string | null;
  phone?: string | null;
  line1?: string | null;
  postalCode?: string | null;
  city?: string | null;
  country?: string | null;
  /**
   * Bei Geschäftskunden im EU-Ausland nötig — dann geht die Rechnung ohne Steuer raus (Reverse Charge).
   */
  vatId?: string | null;
  siret?: string | null;
  /**
   * Wird bei neuen Belegen dieses Lieferanten vorgeschlagen — spart bei wiederkehrenden Rechnungen Zeit.
   */
  defaultCategory?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Leer lassen = wird automatisch aus dem Titel erzeugt
   */
  slug?: string | null;
  /**
   * Ratgeber-Artikel bringen dauerhaft Google-Traffic (z.B. Material- und Pflegetipps)
   */
  type: 'news' | 'ratgeber';
  publishedDate: string;
  coverImage: number | Media;
  /**
   * Wird in der News-Übersicht und beim Facebook-Post verwendet
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Postet Titel, Teaser, Bild und Link auf die Facebook-Seite
   */
  postToFacebook?: boolean | null;
  /**
   * Wird automatisch gesetzt, wenn der Post erfolgreich war
   */
  facebookPostId?: string | null;
  facebookPostError?: string | null;
  /**
   * Postet Titelbild + Teaser auf das verknüpfte Instagram-Business-Konto
   */
  postToInstagram?: boolean | null;
  instagramPostId?: string | null;
  instagramPostError?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Leer lassen = wird automatisch aus dem Titel erzeugt
   */
  slug?: string | null;
  sector: 'kommunal' | 'gewerbe' | 'privat';
  images: (number | Media)[];
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  client?: string | null;
  year?: number | null;
  /**
   * Werden unter der Referenz gezeigt — und die Referenz erscheint umgekehrt auf der Produktseite.
   */
  relatedProducts?: (number | Product)[] | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Nur echte Stimmen mit Einverständnis der Kunden eintragen — erfundene Bewertungen sind wettbewerbswidrig.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  /**
   * z.B. "Familie M." oder "Stadt Naila" — so wie es öffentlich stehen darf
   */
  author: string;
  /**
   * z.B. "Outdoor-Sofa OS, München"
   */
  context?: string | null;
  /**
   * Wird dann auf der Produktseite angezeigt
   */
  product?: (number | null) | Product;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  discountType: 'percent' | 'fixed';
  discountValue: number;
  startDate: string;
  endDate: string;
  appliesTo: 'all' | 'categories' | 'products';
  categories?: (number | Category)[] | null;
  products?: (number | Product)[] | null;
  /**
   * Mit Code: Rabatt gilt nur nach Eingabe im Warenkorb. Ohne Code: Rabatt gilt automatisch.
   */
  code?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending' | 'paid' | 'inProduction' | 'shipped' | 'cancelled';
  /**
   * z.B. „Ende April" oder „KW 18" — wird beim Umstellen auf „In Fertigung" an den Kunden gemeldet.
   */
  expectedReady?: string | null;
  /**
   * Vor dem Umstellen auf „Versendet" eintragen — sie wird in der Versand-Mail an den Kunden mitgeschickt.
   */
  trackingNumber?: string | null;
  /**
   * z.B. der DHL-/Speditions-Link zur Sendungsverfolgung
   */
  trackingUrl?: string | null;
  /**
   * Teil des Links, den der Kunde in seiner Bestellbestätigung bekommt.
   */
  accessToken?: string | null;
  items: {
    product?: (number | null) | Product;
    titleSnapshot: string;
    variantTitle?: string | null;
    color?: string | null;
    quantity: number;
    unitPrice: number;
    id?: string | null;
  }[];
  subtotal: number;
  discount?: number | null;
  shippingTotal?: number | null;
  total: number;
  deliveryMethod: 'shipping' | 'pickup';
  promotionTitle?: string | null;
  customer: {
    name: string;
    email: string;
    phone?: string | null;
  };
  /**
   * Bei Abholung leer
   */
  shippingAddress?: {
    line1?: string | null;
    line2?: string | null;
    postalCode?: string | null;
    city?: string | null;
    country?: string | null;
  };
  paymentProvider?: ('stripe' | 'paypal') | null;
  stripeSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  paypalOrderId?: string | null;
  paypalCaptureId?: string | null;
  customerNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingegangene Anfragen über Kontaktformular, Produktseite und Maßanfertigung.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  type: 'kontakt' | 'produkt' | 'massanfertigung';
  status: 'neu' | 'inBearbeitung' | 'beantwortet' | 'erledigt';
  name: string;
  email: string;
  phone?: string | null;
  message: string;
  /**
   * Bei Anfragen direkt am Artikel
   */
  product?: (number | null) | Product;
  productTitle?: string | null;
  productUrl?: string | null;
  custom?: {
    width?: number | null;
    depth?: number | null;
    height?: number | null;
    color?: string | null;
    purpose?: string | null;
    desiredDate?: string | null;
  };
  attachments?: (number | Media)[] | null;
  locale?: string | null;
  /**
   * Nur im Backend sichtbar.
   */
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-codes".
 */
export interface LoginCode {
  id: number;
  email: string;
  codeHash: string;
  expiresAt: string;
  attempts: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingangsrechnungen, Quittungen und alles, was Geld gekostet hat.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses".
 */
export interface Expense {
  id: number;
  /**
   * Foto oder PDF der Rechnung. Wird für den Steuer-Export mit ausgegeben.
   */
  document?: (number | null) | Media;
  title?: string | null;
  supplier?: (number | null) | Contact;
  /**
   * Falls noch kein Geschäftspartner angelegt ist.
   */
  supplierName?: string | null;
  invoiceNumber?: string | null;
  invoiceDate: string;
  /**
   * Steht ein Zahlungsziel auf dem Beleg, liest die KI es mit. Vorher bleibt es still; ab drei Tagen vor Fälligkeit meldet sich das Büro jeden Tag, bis der Beleg auf „bezahlt" steht.
   */
  dueDate?: string | null;
  netAmount?: number | null;
  vatRate?: number | null;
  vatAmount?: number | null;
  grossAmount: number;
  category:
    | 'material'
    | 'werkzeug'
    | 'fremdleistung'
    | 'fahrzeug'
    | 'miete'
    | 'versicherung'
    | 'buero'
    | 'werbung'
    | 'reise'
    | 'gebuehren'
    | 'sonstiges';
  paymentMethod?: ('ueberweisung' | 'karte' | 'bar' | 'lastschrift' | 'paypal') | null;
  paid?: boolean | null;
  reminderSentAt?: string | null;
  /**
   * Abwählen bei privaten Anteilen — erscheint dann nicht im Steuer-Export.
   */
  deductible?: boolean | null;
  notes?: string | null;
  /**
   * Ergebnis der KI-Auslesung — bitte immer gegen den Beleg prüfen.
   */
  extraction?: {
    status?: ('ungeprueft' | 'bestaetigt' | 'fehler') | null;
    confidence?: number | null;
    note?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  quoteNumber?: string | null;
  status: 'entwurf' | 'versendet' | 'angenommen' | 'abgelehnt';
  title?: string | null;
  customer?: (number | null) | Contact;
  customerName?: string | null;
  customerAddress?: string | null;
  issueDate?: string | null;
  /**
   * Bei Stahlpreisen üblich: 30 Tage.
   */
  validUntil?: string | null;
  items?:
    | {
        description: string;
        quantity: number;
        unit?: string | null;
        unitPrice: number;
        vatRate: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Wird anteilig auf die Positionen verteilt, damit die Steuer stimmt.
   */
  discountKind?: ('kein' | 'prozent' | 'betrag') | null;
  discountValue?: number | null;
  /**
   * Steht so auf dem Angebot, z.B. „Projektnachlass".
   */
  discountReason?: string | null;
  subtotal?: number | null;
  discountTotal?: number | null;
  netTotal?: number | null;
  vatTotal?: number | null;
  total?: number | null;
  /**
   * Zählt bei jeder Änderung nach dem Versenden hoch. Die Nummer bleibt.
   */
  revision?: number | null;
  revisedAt?: string | null;
  /**
   * z.B. „6–8 Wochen ab Auftragserteilung"
   */
  productionTime?: string | null;
  note?: string | null;
  inquiry?: (number | null) | Inquiry;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  jobNumber?: string | null;
  /**
   * Bei einer Shop-Bestellung löst „In Fertigung" die E-Mail an die Kundschaft aus.
   */
  status: 'geplant' | 'inFertigung' | 'fertig' | 'geliefert' | 'abgebrochen';
  title: string;
  source: 'shop' | 'angebot' | 'manuell';
  customerName?: string | null;
  contact?: (number | null) | Contact;
  startDate?: string | null;
  /**
   * Wird der Kundschaft als voraussichtlicher Termin gemeldet.
   */
  dueDate?: string | null;
  positions?:
    | {
        description: string;
        quantity?: number | null;
        /**
         * Bei Shop-Bestellungen der Preis von der Website.
         */
        price?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Wird erst beim Abschließen des Auftrags vom Inventar abgezogen — vorher ist es nur Planung.
   */
  material?:
    | {
        item: number | InventoryItem;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  materialGebucht?: boolean | null;
  notes?: string | null;
  order?: (number | null) | Order;
  quote?: (number | null) | Quote;
  /**
   * Muss auf Auftragsbestätigung und Rechnung stehen.
   */
  customerOrderRef?: string | null;
  orderedAt?: string | null;
  /**
   * Wird beim Erzeugen der Bestätigung gesetzt.
   */
  confirmedAt?: string | null;
  /**
   * Bestellschein, Mail-Ausdruck oder Auftragsschreiben.
   */
  orderDocument?: (number | null) | Media;
  invoice?: (number | null) | OutgoingInvoice;
  project?: (number | null) | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * Rechnungen an Kommunen, Gewerbe und Privat außerhalb des Shops.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outgoing-invoices".
 */
export interface OutgoingInvoice {
  id: number;
  /**
   * Wird beim Festschreiben automatisch und lückenlos vergeben.
   */
  invoiceNumber?: string | null;
  /**
   * Ab „Gestellt" bekommt die Rechnung ihre Nummer und ist verbindlich.
   */
  status: 'entwurf' | 'gestellt' | 'bezahlt' | 'storniert';
  customer?: (number | null) | Contact;
  customerName?: string | null;
  /**
   * Wird aus dem Geschäftspartner übernommen, wenn dort hinterlegt.
   */
  customerAddress?: string | null;
  issueDate?: string | null;
  dueDate?: string | null;
  paidDate?: string | null;
  items?:
    | {
        description: string;
        quantity: number;
        unit?: string | null;
        unitPrice: number;
        vatRate: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Ein gewährter Nachlass muss auf der Rechnung stehen — er wird anteilig auf die Positionen verteilt, damit die Steuer stimmt.
   */
  discountKind?: ('kein' | 'prozent' | 'betrag') | null;
  discountValue?: number | null;
  discountReason?: string | null;
  discountTotal?: number | null;
  netTotal?: number | null;
  subtotal?: number | null;
  vatTotal?: number | null;
  total?: number | null;
  /**
   * Bei Geschäftskunden im EU-Ausland mit gültiger USt-IdNr. — dann alle Sätze auf 0 setzen; der Hinweis erscheint auf der Rechnung.
   */
  reverseCharge?: boolean | null;
  /**
   * z.B. Bezug zum Angebot oder Zahlungsziel-Abrede.
   */
  note?: string | null;
  /**
   * Optional — verbindet die Rechnung mit dem gezeigten Projekt.
   */
  project?: (number | null) | Project;
  /**
   * Wird beim Umwandeln eines Angebots gesetzt.
   */
  quote?: (number | null) | Quote;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stocktakes".
 */
export interface Stocktake {
  id: number;
  title: string;
  date: string;
  status: 'offen' | 'abgeschlossen';
  lines?:
    | {
        item: number | InventoryItem;
        expected?: number | null;
        counted: number;
        /**
         * Stand zum Stichtag — wird beim Anlegen übernommen.
         */
        unitValue?: number | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  totalValue?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counters".
 */
export interface Counter {
  id: number;
  key: string;
  lastNumber: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-state".
 */
export interface SystemState {
  id: number;
  key: string;
  lastRun?: string | null;
  ok?: boolean | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-log".
 */
export interface MailLog {
  id: number;
  to: string;
  from?: string | null;
  subject: string;
  status: 'gesendet' | 'fehler' | 'ohneVersand';
  kind?: ('bestellung' | 'fertigung' | 'versand' | 'anfrage' | 'zugangscode' | 'postfach' | 'sonstiges') | null;
  /**
   * Antwort des Mailservers, wenn der Versand nicht geklappt hat.
   */
  error?: string | null;
  /**
   * Dateinamen, durch Komma getrennt.
   */
  attachments?: string | null;
  order?: (number | null) | Order;
  inquiry?: (number | null) | Inquiry;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: number;
  endpoint: string;
  p256dh: string;
  auth: string;
  label?: string | null;
  user?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Nur die Inhaberrolle sieht Belege, Rechnungen, Inventar und den Steuer-Export unter /office.
   */
  role: 'redaktion' | 'inhaber';
  /**
   * Wird über die Einrichtung unten aktiviert.
   */
  mfaEnabled?: boolean | null;
  mfaSecret?: string | null;
  mfaPendingSecret?: string | null;
  mfaBackupCodes?:
    | {
        hash?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'login-codes';
        value: number | LoginCode;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'expenses';
        value: number | Expense;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'outgoing-invoices';
        value: number | OutgoingInvoice;
      } | null)
    | ({
        relationTo: 'inventory-items';
        value: number | InventoryItem;
      } | null)
    | ({
        relationTo: 'stocktakes';
        value: number | Stocktake;
      } | null)
    | ({
        relationTo: 'counters';
        value: number | Counter;
      } | null)
    | ({
        relationTo: 'system-state';
        value: number | SystemState;
      } | null)
    | ({
        relationTo: 'mail-log';
        value: number | MailLog;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: number | PushSubscription;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  images?: T;
  shortDescription?: T;
  description?: T;
  price?: T;
  shippingCost?: T;
  variants?:
    | T
    | {
        title?: T;
        price?: T;
        id?: T;
      };
  colorOptions?:
    | T
    | {
        name?: T;
        hex?: T;
        id?: T;
      };
  billOfMaterials?:
    | T
    | {
        item?: T;
        quantity?: T;
        note?: T;
        id?: T;
      };
  serviceProviders?:
    | T
    | {
        contact?: T;
        service?: T;
        cost?: T;
        leadTime?: T;
        note?: T;
        id?: T;
      };
  productionTime?: T;
  readyMade?: T;
  onRequestOnly?: T;
  available?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  parent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  publishedDate?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  postToFacebook?: T;
  facebookPostId?: T;
  facebookPostError?: T;
  postToInstagram?: T;
  instagramPostId?: T;
  instagramPostError?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sector?: T;
  images?: T;
  summary?: T;
  description?: T;
  client?: T;
  year?: T;
  relatedProducts?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  context?: T;
  product?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  discountType?: T;
  discountValue?: T;
  startDate?: T;
  endDate?: T;
  appliesTo?: T;
  categories?: T;
  products?: T;
  code?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  expectedReady?: T;
  trackingNumber?: T;
  trackingUrl?: T;
  accessToken?: T;
  items?:
    | T
    | {
        product?: T;
        titleSnapshot?: T;
        variantTitle?: T;
        color?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  subtotal?: T;
  discount?: T;
  shippingTotal?: T;
  total?: T;
  deliveryMethod?: T;
  promotionTitle?: T;
  customer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  paymentProvider?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  paypalOrderId?: T;
  paypalCaptureId?: T;
  customerNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  product?: T;
  productTitle?: T;
  productUrl?: T;
  custom?:
    | T
    | {
        width?: T;
        depth?: T;
        height?: T;
        color?: T;
        purpose?: T;
        desiredDate?: T;
      };
  attachments?: T;
  locale?: T;
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "login-codes_select".
 */
export interface LoginCodesSelect<T extends boolean = true> {
  email?: T;
  codeHash?: T;
  expiresAt?: T;
  attempts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  email?: T;
  phone?: T;
  line1?: T;
  postalCode?: T;
  city?: T;
  country?: T;
  vatId?: T;
  siret?: T;
  defaultCategory?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses_select".
 */
export interface ExpensesSelect<T extends boolean = true> {
  document?: T;
  title?: T;
  supplier?: T;
  supplierName?: T;
  invoiceNumber?: T;
  invoiceDate?: T;
  dueDate?: T;
  netAmount?: T;
  vatRate?: T;
  vatAmount?: T;
  grossAmount?: T;
  category?: T;
  paymentMethod?: T;
  paid?: T;
  reminderSentAt?: T;
  deductible?: T;
  notes?: T;
  extraction?:
    | T
    | {
        status?: T;
        confidence?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  status?: T;
  title?: T;
  customer?: T;
  customerName?: T;
  customerAddress?: T;
  issueDate?: T;
  validUntil?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        unit?: T;
        unitPrice?: T;
        vatRate?: T;
        id?: T;
      };
  discountKind?: T;
  discountValue?: T;
  discountReason?: T;
  subtotal?: T;
  discountTotal?: T;
  netTotal?: T;
  vatTotal?: T;
  total?: T;
  revision?: T;
  revisedAt?: T;
  productionTime?: T;
  note?: T;
  inquiry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  jobNumber?: T;
  status?: T;
  title?: T;
  source?: T;
  customerName?: T;
  contact?: T;
  startDate?: T;
  dueDate?: T;
  positions?:
    | T
    | {
        description?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  material?:
    | T
    | {
        item?: T;
        quantity?: T;
        id?: T;
      };
  materialGebucht?: T;
  notes?: T;
  order?: T;
  quote?: T;
  customerOrderRef?: T;
  orderedAt?: T;
  confirmedAt?: T;
  orderDocument?: T;
  invoice?: T;
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "outgoing-invoices_select".
 */
export interface OutgoingInvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  status?: T;
  customer?: T;
  customerName?: T;
  customerAddress?: T;
  issueDate?: T;
  dueDate?: T;
  paidDate?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        unit?: T;
        unitPrice?: T;
        vatRate?: T;
        id?: T;
      };
  discountKind?: T;
  discountValue?: T;
  discountReason?: T;
  discountTotal?: T;
  netTotal?: T;
  subtotal?: T;
  vatTotal?: T;
  total?: T;
  reverseCharge?: T;
  note?: T;
  project?: T;
  quote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-items_select".
 */
export interface InventoryItemsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  quantity?: T;
  unit?: T;
  minQuantity?: T;
  unitValue?: T;
  location?: T;
  purchaseDate?: T;
  purchaseValue?: T;
  supplier?: T;
  product?: T;
  photo?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stocktakes_select".
 */
export interface StocktakesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  status?: T;
  lines?:
    | T
    | {
        item?: T;
        expected?: T;
        counted?: T;
        unitValue?: T;
        note?: T;
        id?: T;
      };
  totalValue?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counters_select".
 */
export interface CountersSelect<T extends boolean = true> {
  key?: T;
  lastNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-state_select".
 */
export interface SystemStateSelect<T extends boolean = true> {
  key?: T;
  lastRun?: T;
  ok?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mail-log_select".
 */
export interface MailLogSelect<T extends boolean = true> {
  to?: T;
  from?: T;
  subject?: T;
  status?: T;
  kind?: T;
  error?: T;
  attachments?: T;
  order?: T;
  inquiry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  label?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  mfaEnabled?: T;
  mfaSecret?: T;
  mfaPendingSecret?: T;
  mfaBackupCodes?:
    | T
    | {
        hash?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroSlides?:
    | {
        image: number | Media;
        /**
         * Läuft stumm in Schleife statt des Bilds; das Bild bleibt Poster/Fallback. Kurze Clips (10–20 s, ohne Ton) verwenden.
         */
        video?: (number | null) | Media;
        title?: string | null;
        subtitle?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  missionTitle?: string | null;
  missionText?: string | null;
  gallery?: (number | Media)[] | null;
  highlights?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  values?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  heroImage?: (number | null) | Media;
  title?: string | null;
  intro?: string | null;
  timeline?:
    | {
        /**
         * z.B. "2025" oder "seit 2020"
         */
        year: string;
        title: string;
        text?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  contact?: {
    phone?: string | null;
    email?: string | null;
    company?: string | null;
    address?: string | null;
  };
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  /**
   * Pflichtangaben für Bestellbestätigungen (französische SAS): SIRET und TVA-Nummer erscheinen in der Fußzeile der Bestell-Mails.
   */
  company?: {
    /**
     * Wie im Handelsregister eingetragen, z.B. „Next-Concept SAS".
     */
    legalName?: string | null;
    /**
     * Muss auf jeder Rechnung stehen.
     */
    legalForm?: string | null;
    /**
     * Bei einer SAS Pflichtangabe auf Rechnungen.
     */
    shareCapital?: number | null;
    /**
     * Handelsregisternummer
     */
    rcsNumber?: string | null;
    /**
     * Stadt der Eintragung, z.B. „RCS Colmar"
     */
    rcsCity?: string | null;
    address?: string | null;
    siret?: string | null;
    /**
     * z.B. FR12345678901
     */
    vatId?: string | null;
    paymentTerms?: string | null;
    /**
     * Bei Rechnungen an Geschäftskunden Pflicht. Vorschlag: „Bei Zahlungsverzug werden Verzugszinsen in Höhe des dreifachen gesetzlichen Zinssatzes sowie eine Pauschale für Beitreibungskosten von 40 € fällig." — Wortlaut mit dem Steuerberater abstimmen.
     */
    latePaymentNote?: string | null;
    /**
     * Beim Verkauf an Privatkunden in Frankreich Pflicht: Name und Anschrift des Médiateur de la consommation.
     */
    mediator?: string | null;
    /**
     * Wird für den Steuerausweis aus den Bruttopreisen herausgerechnet (Frankreich: 20). Hinweis: Ab 10.000 € EU-Fernverkauf/Jahr greift das OSS-Verfahren — mit dem Steuerberater klären.
     */
    vatRate?: number | null;
  };
  /**
   * Es gibt keine Serienfertigung — jedes Stück entsteht einzeln. Diese Texte erscheinen am Produkt, in der Kasse und in den Bestellmails.
   */
  craft?: {
    /**
     * Kündigt Abweichungen vor dem Kauf an — das ist der rechtlich saubere Weg.
     */
    notice?: string | null;
    /**
     * Gilt für alle Produkte ohne eigene Angabe, z.B. „3–4 Wochen".
     */
    defaultProductionTime?: string | null;
  };
  /**
   * Für cookiefreie Statistik wie selbst gehostetes Plausible oder Umami — dann ist kein Cookie-Banner nötig. Leer lassen = keine Statistik.
   */
  analytics?: {
    /**
     * z.B. https://statistik.example.com/script.js
     */
    scriptUrl?: string | null;
    /**
     * z.B. vincent-hellmann.com
     */
    domain?: string | null;
  };
  /**
   * Der Code aus dem Pinterest-Meta-Tag (Business-Konto → Einstellungen → Website beanspruchen). Nur der content-Wert, nicht das ganze Tag.
   */
  pinterestVerification?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  impressum?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  datenschutz?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  agb?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Zugangsdaten für E-Mail-Versand, Stripe und Facebook. Leere Felder nutzen die im Server hinterlegten Umgebungsvariablen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  email?: {
    /**
     * z.B. smtp.strato.de
     */
    smtpHost?: string | null;
    /**
     * 587 (STARTTLS) oder 465 (SSL)
     */
    smtpPort?: number | null;
    smtpUser?: string | null;
    smtpPass?: string | null;
    /**
     * z.B. info@vincent-hellmann.com
     */
    fromAddress?: string | null;
    /**
     * z.B. Vincent Hellmann
     */
    fromName?: string | null;
    /**
     * Empfängt Kontaktanfragen und Bestell-Benachrichtigungen
     */
    notificationEmail?: string | null;
  };
  /**
   * Schlüssel für die Push-Benachrichtigungen der Büro-App. Wird beim ersten Mal automatisch erzeugt — hier ist nichts einzutragen. Wer den Schlüssel austauscht, muss alle Geräte neu anmelden.
   */
  push?: {
    publicKey?: string | null;
    privateKey?: string | null;
    /**
     * Verlangen die Push-Dienste, falls es Rückfragen zum Versand gibt.
     */
    subject?: string | null;
  };
  /**
   * Postfächer, die im Büro unter /office/post gelesen und beantwortet werden — z.B. info@ und bestellungen@. Die Website selbst verschickt weiterhin über die Absenderadresse oben (noreply@), die hier nicht eingetragen werden muss.
   */
  mailboxes?:
    | {
        /**
         * z.B. „Info" — steht so in der Auswahl im Büro.
         */
        label: string;
        /**
         * Wird beim Antworten als Absender verwendet.
         */
        address: string;
        isDefault?: boolean | null;
        /**
         * z.B. imap.strato.de
         */
        imapHost: string;
        /**
         * 993 (SSL) oder 143 (STARTTLS)
         */
        imapPort?: number | null;
        imapSecure?: boolean | null;
        user: string;
        /**
         * Wird nur serverseitig verwendet und nie an den Browser ausgeliefert.
         */
        pass: string;
        /**
         * Bei manchen Anbietern „Gesendete Objekte" oder „INBOX.Sent".
         */
        sentMailbox?: string | null;
        trashMailbox?: string | null;
        /**
         * Wird unter jede Mail gesetzt, die aus dem Büro rausgeht. Ohne Eintrag entsteht sie aus Absendername und den Kontaktdaten der Website-Einstellungen. Firmierung, SIRET und TVA werden ohnehin automatisch angehängt — das ist Pflicht.
         */
        signature?: string | null;
        /**
         * Nur nötig, wenn dieses Postfach über einen anderen Server verschickt als oben eingestellt.
         */
        smtpHost?: string | null;
        smtpPort?: number | null;
        smtpUser?: string | null;
        smtpPass?: string | null;
        id?: string | null;
      }[]
    | null;
  stripe?: {
    /**
     * sk_test_… oder sk_live_… (Stripe-Dashboard → API-Keys)
     */
    secretKey?: string | null;
    /**
     * whsec_… des Webhook-Endpunkts /api/stripe-webhook
     */
    webhookSecret?: string | null;
  };
  paypal?: {
    /**
     * Aus dem PayPal-Developer-Dashboard (REST-App)
     */
    clientId?: string | null;
    clientSecret?: string | null;
    /**
     * Aktivieren, solange mit Sandbox-Zugangsdaten getestet wird
     */
    sandbox?: boolean | null;
  };
  /**
   * Schlüssel von console.anthropic.com. Damit liest die Verwaltung hochgeladene Belege aus und schlägt Texte und Übersetzungen vor. Ohne Schlüssel bleiben diese Knöpfe einfach aus.
   */
  anthropic?: {
    /**
     * Beginnt mit sk-ant-…
     */
    apiKey?: string | null;
    /**
     * Nur ändern, wenn es einen Grund gibt. Standard: claude-opus-5.
     */
    model?: string | null;
  };
  /**
   * Zugang für die Verwaltung per Claude. Ohne Schlüssel ist der Endpunkt abgeschaltet.
   */
  mcp?: {
    /**
     * Wirkt wie ein Admin-Passwort — nur an vertrauenswürdige Geräte weitergeben.
     */
    apiKey?: string | null;
    /**
     * Optional. Mit diesem Schlüssel lassen sich Inhalte und Auswertungen nur ansehen.
     */
    readonlyKey?: string | null;
  };
  /**
   * Jede Sicherung enthält die vollständige Datenbank und alle Bilder. Ohne zweiten Ort ist sie nur eine Schönwetter-Kopie — deshalb hier die NAS eintragen. Bedient wird das Ganze im Büro unter Sicherung.
   */
  sicherung?: {
    protokoll?: ('smb' | 'webdav') | null;
    smbServer?: string | null;
    smbFreigabe?: string | null;
    /**
     * Optional, z.B. sicherungen/vh — der Ordner muss auf der NAS schon bestehen.
     */
    smbPfad?: string | null;
    smbBenutzer?: string | null;
    smbPasswort?: string | null;
    webdavUrl?: string | null;
    webdavBenutzer?: string | null;
    /**
     * Bei Nextcloud/ownCloud ein App-Passwort verwenden.
     */
    webdavPasswort?: string | null;
    automatik?: boolean | null;
    /**
     * Format HH:MM, Zeitzone des Servers.
     */
    uhrzeit?: string | null;
    behaltenLokal?: number | null;
    behaltenNas?: number | null;
  };
  facebook?: {
    pageId?: string | null;
    /**
     * Langlebiger Token einer Meta-App mit pages_manage_posts (für Instagram zusätzlich instagram_content_publish)
     */
    accessToken?: string | null;
    /**
     * ID des mit der Facebook-Seite verknüpften Instagram-Business-Kontos — nur nötig für den Instagram-Autopost
     */
    instagramAccountId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        image?: T;
        video?: T;
        title?: T;
        subtitle?: T;
        link?: T;
        id?: T;
      };
  missionTitle?: T;
  missionText?: T;
  gallery?: T;
  highlights?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  values?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heroImage?: T;
  title?: T;
  intro?: T;
  timeline?:
    | T
    | {
        year?: T;
        title?: T;
        text?: T;
        image?: T;
        id?: T;
      };
  gallery?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        company?: T;
        address?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  company?:
    | T
    | {
        legalName?: T;
        legalForm?: T;
        shareCapital?: T;
        rcsNumber?: T;
        rcsCity?: T;
        address?: T;
        siret?: T;
        vatId?: T;
        paymentTerms?: T;
        latePaymentNote?: T;
        mediator?: T;
        vatRate?: T;
      };
  craft?:
    | T
    | {
        notice?: T;
        defaultProductionTime?: T;
      };
  analytics?:
    | T
    | {
        scriptUrl?: T;
        domain?: T;
      };
  pinterestVerification?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  impressum?: T;
  datenschutz?: T;
  agb?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  email?:
    | T
    | {
        smtpHost?: T;
        smtpPort?: T;
        smtpUser?: T;
        smtpPass?: T;
        fromAddress?: T;
        fromName?: T;
        notificationEmail?: T;
      };
  push?:
    | T
    | {
        publicKey?: T;
        privateKey?: T;
        subject?: T;
      };
  mailboxes?:
    | T
    | {
        label?: T;
        address?: T;
        isDefault?: T;
        imapHost?: T;
        imapPort?: T;
        imapSecure?: T;
        user?: T;
        pass?: T;
        sentMailbox?: T;
        trashMailbox?: T;
        signature?: T;
        smtpHost?: T;
        smtpPort?: T;
        smtpUser?: T;
        smtpPass?: T;
        id?: T;
      };
  stripe?:
    | T
    | {
        secretKey?: T;
        webhookSecret?: T;
      };
  paypal?:
    | T
    | {
        clientId?: T;
        clientSecret?: T;
        sandbox?: T;
      };
  anthropic?:
    | T
    | {
        apiKey?: T;
        model?: T;
      };
  mcp?:
    | T
    | {
        apiKey?: T;
        readonlyKey?: T;
      };
  sicherung?:
    | T
    | {
        protokoll?: T;
        smbServer?: T;
        smbFreigabe?: T;
        smbPfad?: T;
        smbBenutzer?: T;
        smbPasswort?: T;
        webdavUrl?: T;
        webdavBenutzer?: T;
        webdavPasswort?: T;
        automatik?: T;
        uhrzeit?: T;
        behaltenLokal?: T;
        behaltenNas?: T;
      };
  facebook?:
    | T
    | {
        pageId?: T;
        accessToken?: T;
        instagramAccountId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}